---
title: |
  Cleaning biomarker datasets
author: "Sajia Darwish"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
---
# Make a cleaning function
```{r message=FALSE, warning=FALSE}
library(naniar)
library(tidyverse)

# Make a cleaning function
cleanFunc <- function(data) {
  
  # Change <LOD to NA.
  data[data == "< LOD"] <- NA
  
  # Change these values to min/2.
  data <- data %>% 
    mutate_if(is.numeric, function(x) ifelse(is.na(x), min(x, na.rm = T) / 2, x))
  
  # Change Inf values to 0.
  data[data == Inf] <- 0
  
  # Check for missingness.
  #table(is.na(data))
  
  # Remove columns with no variance.
  #data <- data[, which(apply(data, 2, var) > 0)]
  #str(data)
  
  return(data)
}
```

# HMO ELICIT
```{r}
hmo <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/hmo.RDS")

# Filter out obs without Y
hmo <- hmo %>%
  filter(!is.na(haz_6m))

hmoClean <- cleanFunc(hmo)

# Convert sex_base to binary.
hmoClean $ sex_base = ifelse(hmoClean $ sex_base == "Male", 0, 1)

# Look at columns with NA
hmoClean <- data.frame(hmoClean)

# Get mean and variance of the outcome
mean <- mean(hmoClean $ haz_6m)
sd <- sd(hmoClean $ haz_6m)

# Generate new data from this distribution
hmoClean $ haz_6m_simulated <- rnorm(n = nrow(hmoClean), mean = mean, sd = sd)
hmoClean $ haz_6m_simulated <- as.numeric(format(round(hmoClean $ haz_6m_simulated, 2), 
                                            nsmall = 2))

#saveRDS(hmoClean, file = paste0("/data/imic/data/raw_lab_data/elicit/merged_elicit/hmoClean.RDS"))
```

# Biocrates ELICIT
```{r}
bioc <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/biocratesNorm.RDS")
#biocClean <- cleanFunc(bioc)

# Filter out obs without Y
bioc <- bioc %>%
  filter(!is.na(haz_6m))

biocClean <- cleanFunc(bioc)

# Convert sex_base to binary.
biocClean $ sex_base = ifelse(biocClean $ sex_base == "Male", 0, 1)

# Look at columns with NA
biocClean <- data.frame(biocClean)
percentMissing <- gg_miss_var(biocClean, show_pct = T)

# Delete columns with 100% NA
newData <- biocClean[, -which(colMeans(is.na(biocClean)) == 1)]
gg_miss_var(newData, show_pct = T)

newData <- newData[ - as.numeric(which(apply(newData, 2, var) == 0))]
gg_miss_var(newData, show_pct = T)

newData <- newData[, -which(colMeans(is.na(newData)) > 0.001)]

# Keep anything less than ~20% LOD and compute values.
# Impute the below LOD values?

# Get mean and variance of the outcome
hist(newData $ haz_6m)
mean <- mean(newData $ haz_6m)
sd <- sd(newData $ haz_6m)

# Generate new data from this distribution
newData $ haz_6m_simulated <- rnorm(n = 199, mean = mean, sd = sd)
newData $ haz_6m_simulated <- as.numeric(format(round(newData $ haz_6m_simulated, 2), 
                                            nsmall = 2))

saveRDS(newData, file = paste0("/data/imic/data/raw_lab_data/elicit/merged_elicit/biocNormClean.RDS"))
```

# Bvitamins ELICIT
```{r}
# Load data
bvit <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/bvit.RDS")

# Filter out obs without Y
bvit <- bvit %>%
  filter(!is.na(haz_6m))

bvitClean <- cleanFunc(bvit)

# Convert sex_base to binary.
bvitClean $ sex_base = ifelse(bvitClean $ sex_base == "Male", 0, 1)

# Look at columns with NA
bvitClean <- data.frame(bvitClean)
percentMissing <- gg_miss_var(bvitClean, show_pct = T)

# Get mean and variance of the outcome
hist(bvitClean $ haz_6m)
mean <- mean(bvitClean $ haz_6m)
sd <- sd(bvitClean $ haz_6m)

# Generate new data from this distribution
bvitClean $ haz_6m_simulated <- rnorm(n = 199, mean = mean, sd = sd)
bvitClean $ haz_6m_simulated <- as.numeric(format(round(bvitClean $ haz_6m_simulated, 2), 
                                            nsmall = 2))

saveRDS(bvitClean, file = paste0("/data/imic/data/raw_lab_data/elicit/merged_elicit/bvitClean.RDS"))
```

# Metabolomics ELICIT
```{r}
# Load data
metabol <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/metabolInd.RDS")

# Filter out obs without Y
metabol <- metabol %>%
  filter(!is.na(haz_6m))

metabolClean <- cleanFunc(metabol)

# Convert sex_base to binary.
metabolClean $ sex_base = ifelse(metabolClean $ sex_base == "Male", 0, 1)

# Look at columns with NA
metabolClean <- data.frame(metabolClean)
percentMissing <- gg_miss_var(metabolClean, show_pct = T)

# Get mean and variance of the outcome
hist(metabolClean $ haz_6m)
mean <- mean(metabolClean $ haz_6m)
sd <- sd(metabolClean $ haz_6m)

# Generate new data from this distribution
metabolClean $ haz_6m_simulated <- rnorm(n = 199, mean = mean, sd = sd)
metabolClean $ haz_6m_simulated <- as.numeric(format(round(metabolClean $ haz_6m_simulated, 2), 
                                            nsmall = 2))

saveRDS(metabolClean, file = paste0("/data/imic/data/raw_lab_data/elicit/merged_elicit/metabolClean.RDS"))
```

# Sapient ELICIT
```{r}
sapient <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/sapient.RDS")

# Filter out obs without Y
sapient <- sapient %>%
  filter(!is.na(haz_6m))

sapient[sapient == "< LOD"] <- NA

library(data.table)
setDT(sapient)
sapient[, lapply(.SD, function(x) ifelse(is.na(x), min(x, na.rm = T) / 2, x)), .SDcols = is.numeric]

# Change Inf values to 0.
sapient[sapient == Inf] <- 0

#sapientClean <- cleanFunc(sapient)

# Convert sex_base to binary.
sapient $ sex_base = ifelse(sapient $ sex_base == "Male", 0, 1)

saveRDS(sapient, file = paste0("/data/imic/data/raw_lab_data/elicit/merged_elicit/sapientClean.RDS"))
```

# HMO VITAL
```{r}
hmo <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/hmo.RDS")
#biocClean <- cleanFunc(bioc)
#names(hmo)

# Filter out obs without Y
hmo <- hmo %>%
  filter(!is.na(haz_m6))

hmoClean <- cleanFunc(hmo)

# Convert sex_base to binary.
hmoClean $ sex_base = ifelse(hmoClean $ sex_base == "Male", 0, 1)

# Look at columns with NA
hmoClean <- data.frame(hmoClean)
percentMissing <- gg_miss_var(hmoClean, show_pct = T)

# Get mean and variance of the outcome
hist(hmoClean $ haz_m6)
mean <- mean(hmoClean $ haz_m6)
sd <- sd(hmoClean $ haz_m6)

# Generate new data from this distribution
hmoClean $ haz_6m_simulated <- rnorm(n = 147, mean = mean, sd = sd)
hmoClean $ haz_6m_simulated <- as.numeric(format(round(hmoClean $ haz_6m_simulated, 2), 
                                            nsmall = 2))

saveRDS(hmoClean, file = paste0("/data/imic/data/raw_lab_data/vital/merged_vital/hmoClean.RDS"))
```

# Biocrates VITAL
```{r}
bioc <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/biocratesNorm.RDS")
#biocClean <- cleanFunc(bioc)

# Filter out obs without Y
bioc <- bioc %>%
  filter(!is.na(haz_m6))

biocClean <- cleanFunc(bioc)

# Convert sex_base to binary.
biocClean $ sex_base = ifelse(biocClean $ sex_base == "Male", 0, 1)

# Look at columns with NA
biocClean <- data.frame(biocClean)
percentMissing <- gg_miss_var(biocClean, show_pct = T)

# Get mean and variance of the outcome
hist(biocClean $ haz_m6)
mean <- mean(biocClean $ haz_m6)
sd <- sd(biocClean $ haz_m6)

# Generate new data from this distribution
biocClean $ haz_6m_simulated <- rnorm(n = 147, mean = mean, sd = sd)
biocClean $ haz_6m_simulated <- as.numeric(format(round(biocClean $ haz_6m_simulated, 2), 
                                            nsmall = 2))

saveRDS(biocClean, file = paste0("/data/imic/data/raw_lab_data/vital/merged_vital/biocNormClean.RDS"))
```

# Pbl VITAL
```{r}
# Load data
pbl <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/pblNorm.RDS")

# Filter out obs without Y
pbl <- pbl %>%
  filter(!is.na(haz_m6))

pblClean <- cleanFunc(pbl)

# Convert sex_base to binary.
pblClean $ sex_base = ifelse(pblClean $ sex_base == "Male", 0, 1)

# Look at columns with NA
pblClean <- data.frame(pblClean)
percentMissing <- gg_miss_var(pblClean, show_pct = T)

saveRDS(pblClean, file = paste0("/data/imic/data/raw_lab_data/vital/merged_vital/pblClean.RDS"))
```

# Metabolomics VITAL
```{r}
# Load data
metabol <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/metabolInd.RDS")

# Filter out obs without Y
metabol <- metabol %>%
  filter(!is.na(haz_m6))

metabolClean <- cleanFunc(metabol)

# Convert sex_base to binary.
metabolClean $ sex_base = ifelse(metabolClean $ sex_base == "Male", 0, 1)

# Look at columns with NA
metabolClean <- data.frame(metabolClean)
percentMissing <- gg_miss_var(metabolClean, show_pct = T)

# Get mean and variance of the outcome
hist(metabolClean $ haz_m6)
mean <- mean(metabolClean $ haz_m6)
sd <- sd(metabolClean $ haz_m6)

# Generate new data from this distribution
metabolClean $ haz_6m_simulated <- rnorm(n = 147, mean = mean, sd = sd)
metabolClean $ haz_6m_simulated <- as.numeric(format(round(metabolClean $ haz_6m_simulated, 2), 
                                            nsmall = 2))

saveRDS(metabolClean, file = paste0("/data/imic/data/raw_lab_data/vital/merged_vital/metabolClean.RDS"))
```


# Make one dataset with child ID's + baseline covariates + all biomarkers: ELICIT
```{r}
hmo <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/hmoClean.RDS")

# Collapse hmo data into long format
id <- c("bmid_base", "country", "studyid", "subjid", "subjido", 
        "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
        "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
        "meducyrs_base", "h2osrcp_base", "cookplac_base", 
        "epoch_base", "mhtcm_base", "mwtkg_base", 
        "mbmi_base", "dlvloc_base", 
        "wtkg_base", "lencm_base", "bmi_base", "waz_base", 
        "haz_base", "whz_base", "baz_base", "agedays_base", 
        "dur_bf_base", "dur_ebf_base", "haz_6m")

longHmo <- hmo %>%
  select(c(id,
           "X2.FL_nmol.mL", "X3FL_nmol.mL", "DFLac_nmol.mL", "X3.SL_nmol.mL",
           "X6.SL_nmol.mL", "LNT_nmol.mL", "LNnT_nmol.mL", "LNFP.I_nmol.mL", 
           "LNFP.II_nmol.mL", "LNFP.III_nmol.mL", "LSTb_nmol.mL", "LSTc_nmol.mL",
           "DFLNT_nmol.mL", "LNH_nmol.mL", "DSLNT_nmol.mL", "FLNH_nmol.mL", "DFLNH_nmol.mL", 
           "FDSLNH_nmol.mL", "DSLNH_nmol.mL", "SUM_nmol.mL", "Sia_nmol.mL", "Fuc_nmol.mL")) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

bioc <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/biocNormClean.RDS")

A = bioc %>%
  select(!c("bmid_base", "country", "studyid", "subjid", "subjido", "arm_base", 
            "sex_base", "brthyr_base", "brthweek_base", "mage_base", "parity_base", 
            "nlchild_base", "nperson_base", "nrooms_base", "meducyrs_base", 
            "h2osrcp_base", "cookplac_base", "inctot_base", "inctotu_base", 
            "epoch_base", "mhtcm_base", "mwtkg_base", "mbmi_base", "dlvloc_base", 
            "dvseason_base", "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", 
            "waz_base", "haz_base", "whz_base", "baz_base", "agedays_base", 
            "dur_bf_base", "dur_ebf_base", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "exbfdu_r_0to6m", 
            "fever_r_0to6m", "fever_r_6to18m", "cough_r_0to6m", "cough_r_6to18m", 
            "diarr_r_0to6m", "diarr_r_6to18m", "mhgb_18m", "muaccm_18m", 
            "muaz_18m", "bfdu_r_0to18m", "anti_r_0to18m", "haz_6m_simulated"))
A = colnames(A)

longBioc <- bioc %>%
  select(c(id, A)) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

bvit <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/bvitClean.RDS")

A = bvit %>%
  select(!c("bmid_base", "country", "studyid", "siteid", "subjid", "subjido", 
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "inctot_base", 
            "inctotu_base", "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", 
            "mbmi_base", "pregout_base", "dlvloc_base", "dvseason_base", 
            "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", "waz_base", 
            "haz_base", "whz_base", "baz_base", "agedays_base", "feeding_base", 
            "dur_bf_base", "dur_ebf_base", "bmcol_fl_1m", "bmcol_fl_5m", 
            "agedays_1m", "agedays_5m", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "agedays_3m", "agedays_6m", 
            "agedays_9m", "agedays_12m", "agedays_15m", "agedays_18m", "visit_r_fl_0to6m", 
            "visit_r_fl_6to18m", "dur_r_0to6m", "dur_r_6to18m", "bfedfl_r_0to6m", 
            "exbfed_r_0to6m", "exbfdu_r_0to6m", "fever_r_0to6m", "fever_r_6to18m", 
            "cough_r_0to6m", "cough_r_6to18m", "diarr_r_0to6m", "diarr_r_6to18m", 
            "mhgb_18m", "muaccm_18m", "muaz_18m", "agedays_18m.1", "bfdu_r_0to18m", 
            "anti_r_0to18m", "haz_6m_simulated"))
A = colnames(A)

longBvit <- bvit %>%
  select(c(id, A)) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

metabol <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/metabolClean.RDS")

A = metabol %>%
  select(c("X2.Methylbutyrylglycinuria..NBS.", 
          "X7.Alpha.Dehydroxylation.of.Cholic.Acid", "Alpha.Aminobutyric.Acid.Synthesis", 
          "Anserine.Synthesis", "Asparagine.Synthesis", "Asymmetrical.Arginine.Methylation", 
          "Beta.Alanine.Synthesis", "Beta.Oxidation", "Betaine.Synthesis", 
          "Carnosine.Synthesis", "Citrulline.Synthesis", "Cortisone.Synthesis", 
          "Carbamoyl.Phosphate.Synthase.Deficiency..NBS.", "Cysteine.Synthesis", 
          "Cystine.Synthesis", "Dihydrolipoamide.Dehydrogenase.Deficiency..NBS.", 
          "Fischer.Ratio", "Gamma.Aminobutyric.Acid.Synthesis",
          "Global.Arginine.Bioavailability.Ratio",
          "Glycodeoxycholic.Acid.Synthesis.from.Cholic.Acid", "Glutaminase.Activity", 
          "Glutaminolysis.Rate", "Glycine.Conjugation.of.Cholic.Acid", 
          "Glycine.Conjugation.of.Chenodeoxycholic.Acid",
          "Glycine.Conjugation.of.Deoxycholic.Acid", 
          "Glycine.Conjugation.of.Primary.Bile.Acids", "Glycine.Synthesis", 
          "Glutathione.Constituents", "Homoarginine.Synthesis", "Homocysteine.Synthesis", 
          "Hippuric.Acid.Synthesis", "Isobutyryl.Coenzyme.A.Dehydrogenase.Deficiency..NBS.", 
          "Indoleamine.2.3.Dioxygenase.Activity", "Isovaleric.Acidemia..NBS.", 
          "Lactate.Dehydrogenase.Activity", "Malonic.Aciduria..NBS.", "Methionine.Oxidation", 
          "Methylmalonic.Acidemia..NBS.", "Methylenetetrahydrofolate.Reductase.Deficiency..NBS.", 
          "Nitric.Oxide.Synthase.Activity", "Ornithine.Synthesis",
          "Ornithine.Transcarbamylase.Deficiency..NBS.", 
          "para.Cresol.Sulfate.Synthesis", "Phenylethylamine.Synthesis", 
          "Phenylketonuria..NBS.", "Phospholipase.A2.Activity..2.",
          "Phospholipase.A2.Activity..3.", 
          "Phospholipase.A2.Activity..4.", "Phospholipase.A2.Activity..5.", 
          "Phospholipase.A2.Activity..6.", "Polyamine.Synthesis",
          "Ratio.of.Conjugated.Primary.Bile.Acids.to.Unconjugated.Primary.Bile.Acids", 
          "Putrescine.Synthesis", "Ratio.of.Acetylcarnitine.to.Carnitine", 
          "Ratio.of.Chenodeoxycholic.Acid.to.Cholic.Acid",
          "Ratio.of.Docosahexaenoic.Acid.to.Arachidonic.Acid", 
          "Ratio.of.Docosahexaenoic.Acid.to.Eicosapentaenoic.Acid", 
          "Ratio.of.Eicosapentaenoic.Acid.to.Arachidonic.Acid", 
          "Ratio.of.Homoarginine.to.Asymmetric.Dimethylarginine",
          "Ratio.of.Homoarginine.to.Symmetric.Dimethylarginine", 
          "Ratio.of.Non.Essential.to.Essential.Amino.Acids", "Ratio.of.Proline.to.Citrulline", 
          "Ratio.of.Hydroxylated.Sphingomyelins.to.Non.Hydroxylated.Sphingomyelins", 
          "Sarcosine.Synthesis.from.Choline", "Sarcosine.Synthesis.from.Glycine", 
          "Short.Branched.Chain.Acyl.Coenzyme.A.Dehydrogenase.Deficiency..NBS.", 
          "Short.Chain.Acyl.Coenzyme.A.Dehydrogenase.Deficiency..NBS.", 
          "Spermidine.Synthesis", "Spermine.Synthesis", "Sum.of.12.Alpha.Hydroxylated.Bile.Acids", 
          "Sum.of.Amino.Acids", "Sum.of.Aromatic.Amino.Acids", 
          "Sum.of.Asymmetrical.and.Symmetrical.Arginine.Methylation", 
          "Sum.of.Betaine.and.Related.Metabolites", "Sum.of.Betaine.Related.Metabolites", 
          "Sum.of.Branched.Chain.Amino.Acids", "Sum.of.Conjugated.Primary.Bile.Acids", 
          "Sum.of.Dimethylated.Arginines", "Sum.of.Essential.Amino.Acids", 
          "Sum.of.Long.Chain.Fatty.Acid.Lysophosphatidylcholines", 
          "Sum.of.Long.Chain.Fatty.Acid.Sphingomyelins", 
          "Sum.of.Measured.Omega.3.Fatty.Acids", 
          "Sum.of.Monounsaturated.Fatty.Acid.Lysophosphatidylcholines", 
          "Sum.of.Non.Essential.Amino.Acids", "Sum.of.Polyamines", "Sum.of.Primary.Bile.Acids", 
          "Sum.of.Polyunsaturated.Fatty.Acid.Lysophosphatidylcholines", 
          "Sum.of.Purine.Derivatives", "Sum.of.Non.Hydroxylated.Sphingomyelins", 
          "Sum.of.Hydroxylated.Sphingomyelins", "Sum.of.Sphingomyelins", 
          "Sum.of.Solely.Glucogenic.Amino.Acids", "Sum.of.Solely.Ketogenic.Amino.Acids", 
          "Sum.of.Steroid.Hormones", "Sum.of.Sulfur.Containing.Amino.Acids", 
          "Sum.of.Unconjugated.Bile.Acids", "Sum.of.Unconjugated.Primary.Bile.Acids", 
          "Sum.of.Very.Long.Chain.Fatty.Acid.Sphingomyelins", "Symmetrical.Arginine.Methylation", 
          "Taurine.Conjugation.of.Cholic.Acid", "Taurine.Conjugation.of.Chenodeoxycholic.Acid", 
          "Taurine.Conjugation.of.Deoxycholic.Acid", "Taurine.Conjugation.of.Primary.Bile.Acids", 
          "Taurine.Synthesis", "Taurodeoxycholic.Acid.Synthesis.from.Cholic.Acid", 
          "Trimethylamine.N.Oxide.Synthesis", "Trimethylamine.N.Oxide.Synthesis..direct.", 
          "Valinemia..NBS.", "Xanthine.Synthesis", "Ratio.of.Serine.and.Glycine.to.Hexose", 
          "Ratio.of.Serine..Glycine..and.Alanine.to.Hexose"))
A = colnames(A)

longMetabol <- metabol %>%
  select(c(id, A)) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

sapient <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/sapientClean.RDS")

A = sapient %>%
  select(!c("bmid_base", "country", "studyid", "siteid", "subjid", "subjido",
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base",
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base",
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "inctot_base",
            "inctotu_base", "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base",
            "mbmi_base", "pregout_base", "dlvloc_base", "dvseason_base",
            "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", "waz_base",
            "haz_base", "whz_base", "baz_base", "agedays_base", "feeding_base",
            "dur_bf_base", "dur_ebf_base", "bmcol_fl_1m", "bmcol_fl_5m",
            "agedays_1m", "agedays_5m", "lencm_3m", "lencm_6m", "lencm_9m",
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m",
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m",
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m",
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m",
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m",
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m",
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "agedays_3m", "agedays_6m",
            "agedays_9m", "agedays_12m", "agedays_15m", "agedays_18m", "visit_r_fl_0to6m",
            "visit_r_fl_6to18m", "dur_r_0to6m", "dur_r_6to18m", "bfedfl_r_0to6m",
            "exbfed_r_0to6m", "exbfdu_r_0to6m", "fever_r_0to6m", "fever_r_6to18m",
            "cough_r_0to6m", "cough_r_6to18m", "diarr_r_0to6m", "diarr_r_6to18m",
            "mhgb_18m", "muaccm_18m", "muaz_18m", "agedays_18m.1", "bfdu_r_0to18m",
            "anti_r_0to18m"))
A = colnames(A)

longSapient <- sapient %>%
  select(c(id, A)) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

# Combine all datasets
LongDataset <- rbind(longBioc, longBvit)
LongDataset <- rbind(LongDataset, longHmo)
LongDataset <- rbind(LongDataset, longMetabol)
LongDataset <- rbind(LongDataset, longSapient)

# Save dataset
write.csv(LongDataset, file = "/data/imic/data/raw_lab_data/elicit/merged_elicit/longDataset.csv")
```

# Make one dataset with child ID's + baseline covariates + all biomarkers: VITAL
```{r}
hmo <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/hmoClean.RDS")

# Collapse hmo data into long format
id <- c("bmid_base", "country", "studyid", "subjid", "subjido", 
        "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
        "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
        "meducyrs_base", "h2osrcp_base", "cookplac_base", 
        "epoch_base", "mhtcm_base", "mwtkg_base", 
        "mbmi_base", "dlvloc_base", 
        "wtkg_base", "lencm_base", "bmi_base", "waz_base", 
        "haz_base", "whz_base", "baz_base", "agedays_base", 
        "dur_bf_base", "dur_ebf_base", "haz_6m")

longHmo <- hmo %>%
  select(c(id,
           "X2.FL_nmol.mL", "X3FL_nmol.mL", "DFLac_nmol.mL", "X3.SL_nmol.mL",
           "X6.SL_nmol.mL", "LNT_nmol.mL", "LNnT_nmol.mL", "LNFP.I_nmol.mL", 
           "LNFP.II_nmol.mL", "LNFP.III_nmol.mL", "LSTb_nmol.mL", "LSTc_nmol.mL",
           "DFLNT_nmol.mL", "LNH_nmol.mL", "DSLNT_nmol.mL", "FLNH_nmol.mL", "DFLNH_nmol.mL", 
           "FDSLNH_nmol.mL", "DSLNH_nmol.mL", "SUM_nmol.mL", "Sia_nmol.mL", "Fuc_nmol.mL")) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

bioc <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/biocNormClean.RDS")

A = bioc %>%
  select(!c("bmid_base", "country", "studyid", "subjid", "subjido", "arm_base", 
            "sex_base", "brthyr_base", "brthweek_base", "mage_base", "parity_base", 
            "nlchild_base", "nperson_base", "nrooms_base", "meducyrs_base", 
            "h2osrcp_base", "cookplac_base", "inctot_base", "inctotu_base", 
            "epoch_base", "mhtcm_base", "mwtkg_base", "mbmi_base", "dlvloc_base", 
            "dvseason_base", "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", 
            "waz_base", "haz_base", "whz_base", "baz_base", "agedays_base", 
            "dur_bf_base", "dur_ebf_base", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "exbfdu_r_0to6m", 
            "fever_r_0to6m", "fever_r_6to18m", "cough_r_0to6m", "cough_r_6to18m", 
            "diarr_r_0to6m", "diarr_r_6to18m", "mhgb_18m", "muaccm_18m", 
            "muaz_18m", "bfdu_r_0to18m", "anti_r_0to18m", "haz_6m_simulated"))
A = colnames(A)

longBioc <- bioc %>%
  select(c(id, A)) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

pbl <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/pblClean.RDS")

A = pbl %>%
  select(!c("bmid_base", "country", "studyid", "siteid", "subjid", "subjido", 
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "inctot_base", 
            "inctotu_base", "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", 
            "mbmi_base", "pregout_base", "dlvloc_base", "dvseason_base", 
            "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", "waz_base", 
            "haz_base", "whz_base", "baz_base", "agedays_base", "feeding_base", 
            "dur_bf_base", "dur_ebf_base", "bmcol_fl_1m", "bmcol_fl_5m", 
            "agedays_1m", "agedays_5m", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "agedays_3m", "agedays_6m", 
            "agedays_9m", "agedays_12m", "agedays_15m", "agedays_18m", "visit_r_fl_0to6m", 
            "visit_r_fl_6to18m", "dur_r_0to6m", "dur_r_6to18m", "bfedfl_r_0to6m", 
            "exbfed_r_0to6m", "exbfdu_r_0to6m", "fever_r_0to6m", "fever_r_6to18m", 
            "cough_r_0to6m", "cough_r_6to18m", "diarr_r_0to6m", "diarr_r_6to18m", 
            "mhgb_18m", "muaccm_18m", "muaz_18m", "agedays_18m.1", "bfdu_r_0to18m", 
            "anti_r_0to18m", "haz_6m_simulated"))
A = colnames(A)

longBvit <- pbl %>%
  select(c(id, A)) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

metabol <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/metabolClean.RDS")

A = metabol %>%
  select(c("X2.Methylbutyrylglycinuria..NBS.", 
          "X7.Alpha.Dehydroxylation.of.Cholic.Acid", "Alpha.Aminobutyric.Acid.Synthesis", 
          "Anserine.Synthesis", "Asparagine.Synthesis", "Asymmetrical.Arginine.Methylation", 
          "Beta.Alanine.Synthesis", "Beta.Oxidation", "Betaine.Synthesis", 
          "Carnosine.Synthesis", "Citrulline.Synthesis", "Cortisone.Synthesis", 
          "Carbamoyl.Phosphate.Synthase.Deficiency..NBS.", "Cysteine.Synthesis", 
          "Cystine.Synthesis", "Dihydrolipoamide.Dehydrogenase.Deficiency..NBS.", 
          "Fischer.Ratio", "Gamma.Aminobutyric.Acid.Synthesis",
          "Global.Arginine.Bioavailability.Ratio",
          "Glycodeoxycholic.Acid.Synthesis.from.Cholic.Acid", "Glutaminase.Activity", 
          "Glutaminolysis.Rate", "Glycine.Conjugation.of.Cholic.Acid", 
          "Glycine.Conjugation.of.Chenodeoxycholic.Acid",
          "Glycine.Conjugation.of.Deoxycholic.Acid", 
          "Glycine.Conjugation.of.Primary.Bile.Acids", "Glycine.Synthesis", 
          "Glutathione.Constituents", "Homoarginine.Synthesis", "Homocysteine.Synthesis", 
          "Hippuric.Acid.Synthesis", "Isobutyryl.Coenzyme.A.Dehydrogenase.Deficiency..NBS.", 
          "Indoleamine.2.3.Dioxygenase.Activity", "Isovaleric.Acidemia..NBS.", 
          "Lactate.Dehydrogenase.Activity", "Malonic.Aciduria..NBS.", "Methionine.Oxidation", 
          "Methylmalonic.Acidemia..NBS.", "Methylenetetrahydrofolate.Reductase.Deficiency..NBS.", 
          "Nitric.Oxide.Synthase.Activity", "Ornithine.Synthesis",
          "Ornithine.Transcarbamylase.Deficiency..NBS.", 
          "para.Cresol.Sulfate.Synthesis", "Phenylethylamine.Synthesis", 
          "Phenylketonuria..NBS.", "Phospholipase.A2.Activity..2.",
          "Phospholipase.A2.Activity..3.", 
          "Phospholipase.A2.Activity..4.", "Phospholipase.A2.Activity..5.", 
          "Phospholipase.A2.Activity..6.", "Polyamine.Synthesis",
          "Ratio.of.Conjugated.Primary.Bile.Acids.to.Unconjugated.Primary.Bile.Acids", 
          "Putrescine.Synthesis", "Ratio.of.Acetylcarnitine.to.Carnitine", 
          "Ratio.of.Chenodeoxycholic.Acid.to.Cholic.Acid",
          "Ratio.of.Docosahexaenoic.Acid.to.Arachidonic.Acid", 
          "Ratio.of.Docosahexaenoic.Acid.to.Eicosapentaenoic.Acid", 
          "Ratio.of.Eicosapentaenoic.Acid.to.Arachidonic.Acid", 
          "Ratio.of.Homoarginine.to.Asymmetric.Dimethylarginine",
          "Ratio.of.Homoarginine.to.Symmetric.Dimethylarginine", 
          "Ratio.of.Non.Essential.to.Essential.Amino.Acids", "Ratio.of.Proline.to.Citrulline", 
          "Ratio.of.Hydroxylated.Sphingomyelins.to.Non.Hydroxylated.Sphingomyelins", 
          "Sarcosine.Synthesis.from.Choline", "Sarcosine.Synthesis.from.Glycine", 
          "Short.Branched.Chain.Acyl.Coenzyme.A.Dehydrogenase.Deficiency..NBS.", 
          "Short.Chain.Acyl.Coenzyme.A.Dehydrogenase.Deficiency..NBS.", 
          "Spermidine.Synthesis", "Spermine.Synthesis", "Sum.of.12.Alpha.Hydroxylated.Bile.Acids", 
          "Sum.of.Amino.Acids", "Sum.of.Aromatic.Amino.Acids", 
          "Sum.of.Asymmetrical.and.Symmetrical.Arginine.Methylation", 
          "Sum.of.Betaine.and.Related.Metabolites", "Sum.of.Betaine.Related.Metabolites", 
          "Sum.of.Branched.Chain.Amino.Acids", "Sum.of.Conjugated.Primary.Bile.Acids", 
          "Sum.of.Dimethylated.Arginines", "Sum.of.Essential.Amino.Acids", 
          "Sum.of.Long.Chain.Fatty.Acid.Lysophosphatidylcholines", 
          "Sum.of.Long.Chain.Fatty.Acid.Sphingomyelins", 
          "Sum.of.Measured.Omega.3.Fatty.Acids", 
          "Sum.of.Monounsaturated.Fatty.Acid.Lysophosphatidylcholines", 
          "Sum.of.Non.Essential.Amino.Acids", "Sum.of.Polyamines", "Sum.of.Primary.Bile.Acids", 
          "Sum.of.Polyunsaturated.Fatty.Acid.Lysophosphatidylcholines", 
          "Sum.of.Purine.Derivatives", "Sum.of.Non.Hydroxylated.Sphingomyelins", 
          "Sum.of.Hydroxylated.Sphingomyelins", "Sum.of.Sphingomyelins", 
          "Sum.of.Solely.Glucogenic.Amino.Acids", "Sum.of.Solely.Ketogenic.Amino.Acids", 
          "Sum.of.Steroid.Hormones", "Sum.of.Sulfur.Containing.Amino.Acids", 
          "Sum.of.Unconjugated.Bile.Acids", "Sum.of.Unconjugated.Primary.Bile.Acids", 
          "Sum.of.Very.Long.Chain.Fatty.Acid.Sphingomyelins", "Symmetrical.Arginine.Methylation", 
          "Taurine.Conjugation.of.Cholic.Acid", "Taurine.Conjugation.of.Chenodeoxycholic.Acid", 
          "Taurine.Conjugation.of.Deoxycholic.Acid", "Taurine.Conjugation.of.Primary.Bile.Acids", 
          "Taurine.Synthesis", "Taurodeoxycholic.Acid.Synthesis.from.Cholic.Acid", 
          "Trimethylamine.N.Oxide.Synthesis", "Trimethylamine.N.Oxide.Synthesis..direct.", 
          "Valinemia..NBS.", "Xanthine.Synthesis", "Ratio.of.Serine.and.Glycine.to.Hexose", 
          "Ratio.of.Serine..Glycine..and.Alanine.to.Hexose"))
A = colnames(A)

longMetabol <- metabol %>%
  select(c(id, A)) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

sapient <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/sapientClean.RDS")

A = sapient %>%
  select(!c("bmid_base", "country", "studyid", "siteid", "subjid", "subjido", 
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "inctot_base", 
            "inctotu_base", "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", 
            "mbmi_base", "pregout_base", "dlvloc_base", "dvseason_base", 
            "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", "waz_base", 
            "haz_base", "whz_base", "baz_base", "agedays_base", "feeding_base", 
            "dur_bf_base", "dur_ebf_base", "bmcol_fl_1m", "bmcol_fl_5m", 
            "agedays_1m", "agedays_5m", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "agedays_3m", "agedays_6m", 
            "agedays_9m", "agedays_12m", "agedays_15m", "agedays_18m", "visit_r_fl_0to6m", 
            "visit_r_fl_6to18m", "dur_r_0to6m", "dur_r_6to18m", "bfedfl_r_0to6m", 
            "exbfed_r_0to6m", "exbfdu_r_0to6m", "fever_r_0to6m", "fever_r_6to18m", 
            "cough_r_0to6m", "cough_r_6to18m", "diarr_r_0to6m", "diarr_r_6to18m", 
            "mhgb_18m", "muaccm_18m", "muaz_18m", "agedays_18m.1", "bfdu_r_0to18m", 
            "anti_r_0to18m"))
A = colnames(A)

longSapient <- sapient %>%
  select(c(id, A)) %>%
  pivot_longer(!id,
              names_to = "biomarker",
              values_to = "value")

# Combine all datasets
LongDataset <- rbind(longBioc, longBvit)
LongDataset <- rbind(LongDataset, longHmo)
LongDataset <- rbind(LongDataset, longMetabol)
#LongDataset <- rbind(LongDataset, longSapient)

# Save dataset
write.csv(LongDataset, file = "/data/imic/data/raw_lab_data/vital/merged_vital/longDataset.csv")
```












