---
title: |
  SL Model Selection
author: "Sajia Darwish"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(sl3)
library(kableExtra)
library(knitr)
library(skimr)
library(tidyverse)
library(data.table)
library(sl3)
library(SuperLearner)
library(origami)
library(hal9001)
library(polspline)
```

```{r message=FALSE, warning=FALSE}
slModelFunc <- function(data, covars, outcome) {
  
  # create the sl3 task
  task <- make_sl3_Task(
  data = data,
  covariates = covars,
  outcome = outcome
  )
  #dput(sl3_list_learners(c("continuous")))
  
  lrnr_glm <- make_learner(Lrnr_glm)
  lrnr_mean <- make_learner(Lrnr_mean)
  lrnr_glmtree <- make_learner(Lrnr_glmtree)
  lrnr_ranger100 <- make_learner(Lrnr_ranger, num.trees = 100)
  lrnr_gam <- Lrnr_pkg_SuperLearner$new("SL.gam")
  lrnr_bayesglm <- Lrnr_pkg_SuperLearner$new("SL.bayesglm")
  lrn_ridge <- Lrnr_glmnet $ new(alpha = 0)
  lrn_lasso <- Lrnr_glmnet $ new(alpha = 1)
  # spline regressions:
  lrn_polspline <- Lrnr_polspline $ new()
  lrn_earth <- Lrnr_earth $ new()
  # fast highly adaptive lasso (HAL) implementation
  lrn_hal <- Lrnr_hal9001 $ new(max_degree = 2, num_knots = c(3,2), nfolds = 5)
  # tree-based methods
  lrn_ranger <- Lrnr_ranger $ new()
  lrn_xgb <- Lrnr_xgboost $ new()
  
  stack <- make_learner(
    Stack,
    lrnr_glm, lrnr_mean, lrnr_glmtree, 
    lrnr_ranger100, lrnr_gam,
    lrnr_gam, lrnr_bayesglm, lrn_ridge,
    lrn_lasso, lrn_polspline, lrn_earth,
    lrn_hal, lrn_ranger, lrn_xgb
  )
  
  metalearner <- make_learner(Lrnr_nnls)
  
  sl <- make_learner(Lrnr_sl,
    learners = stack,
    metalearner = metalearner
  )
  
  start_time <- proc.time() # start time
  
  set.seed(4197)
  
  sl_fit <- sl$train(task)
  
  runtime_sl_fit <- proc.time() - start_time # end time - start time = run time
  runtime_sl_fit
  
  sl_preds <- sl_fit $ predict()
  results <- sl_fit $ print()

  return(results)
}
```

# Use the function on datasets
```{r}
# Load data
hmo <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/hmoClean.RDS")
#dput(names((hmo)))
#head(data)

covars = c("X2.FL_nmol.mL", "X3FL_nmol.mL", "DFLac_nmol.mL", "X3.SL_nmol.mL",
       "X6.SL_nmol.mL", "LNT_nmol.mL", "LNnT_nmol.mL", "LNFP.I_nmol.mL", 
       "LNFP.II_nmol.mL", "LNFP.III_nmol.mL", "LSTb_nmol.mL", "LSTc_nmol.mL",
       "DFLNT_nmol.mL", "LNH_nmol.mL", "DSLNT_nmol.mL", "FLNH_nmol.mL", 
       "DFLNH_nmol.mL", "FDSLNH_nmol.mL", "DSLNH_nmol.mL", "SUM_nmol.mL", 
       "Sia_nmol.mL", "Fuc_nmol.mL")
outcome = "haz_6m_simulated"

resultHmo <- slModelFunc(hmo, covars = covars, outcome = outcome)
```

```{r}
# Load data
bioc <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/biocNormClean.RDS")
# head(bioc)
# dput(names((bioc)))

A = bioc %>%
  select(!c("bmid_base", "country", "studyid", "subjid", "subjido", "arm_base", 
            "sex_base", "brthyr_base", "brthweek_base", "mage_base", "parity_base", 
            "nlchild_base", "nperson_base", "nrooms_base", "meducyrs_base", 
            "h2osrcp_base", "cookplac_base", "inctot_base", "inctotu_base", 
            "epoch_base", "mhtcm_base", "mwtkg_base", "mbmi_base", "dlvloc_base", 
            "dvseason_base", "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", 
            "waz_base", "haz_base", "whz_base", "baz_base", "agedays_base", 
            "dur_bf_base", "dur_ebf_base", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", "haz_6m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "exbfdu_r_0to6m", 
            "fever_r_0to6m", "fever_r_6to18m", "cough_r_0to6m", "cough_r_6to18m", 
            "diarr_r_0to6m", "diarr_r_6to18m", "mhgb_18m", "muaccm_18m", 
            "muaz_18m", "bfdu_r_0to18m", "anti_r_0to18m", "haz_6m_simulated"))
covars = c("C0", "C2", "C3", "C4", "C12", "C12.1", "C14", "C18", "X1.Met.His", 
          "X3.Met.His", "AABA", "alpha.AAA", "Cit", "Creatinine", "Cystine", 
          "HArg", "Orn", "SDMA", "t4.OH.Pro", "Taurine", "Ala", "Arg", 
          "Asn", "Asp", "Cys", "Gln", "Glu", "Gly", "His", "Ile", "Leu", 
          "Lys", "Met", "Phe", "Ser", "Thr", "Tyr", "Val", "beta.Ala", 
          "GABA", "Spermidine", "H1", "HipAcid", "Cer.d18.1.16.0.", "Cer.d18.1.18.0.", 
          "Cer.d18.1.20.0.", "Cer.d18.1.22.0.", "Cer.d18.1.24.0.", "Cer.d18.1.24.1.", 
          "CE.18.1.", "p.Cresol.SO4", "DG.14.0_18.1.", "DG.14.0_18.2.", 
          "DG.16.0_16.1.", "DG.16.0_18.1.", "DG.16.0_18.2.", "DG.16.0_20.3.", 
          "DG.16.1_18.1.", "DG.16.1_18.2.", "DG.18.1_18.1.", "DG.18.1_18.2.", 
          "DG.18.1_18.3.", "DG.18.1_20.2.", "DG.18.2_18.2.", "DG.18.2_18.3.", 
          "Hex2Cer.d18.1.16.0.", "Hex2Cer.d18.1.18.0.", "Hex2Cer.d18.1.20.0.", 
          "Hex2Cer.d18.1.22.0.", "Hex2Cer.d18.1.24.0.", "Hex2Cer.d18.1.24.1.", 
          "AA", "DHA", "FA.12.0.", "FA.14.0.", "FA.18.1.", "FA.18.2.", 
          "FA.20.3.", "HexCer.d18.1.16.0.", "HexCer.d18.1.18.0.", "HexCer.d18.1.20.0.", 
          "HexCer.d18.1.22.0.", "HexCer.d18.1.23.0.", "HexCer.d18.1.24.0.", 
          "HexCer.d18.1.24.1.", "lysoPC.a.C16.0", "PC.aa.C28.1", "PC.aa.C30.0", 
          "PC.aa.C32.0", "PC.aa.C32.2", "PC.aa.C34.1", "PC.aa.C34.2", "PC.aa.C34.3", 
          "PC.aa.C36.1", "PC.aa.C36.2", "PC.aa.C36.3", "PC.aa.C36.4", "PC.aa.C38.0", 
          "PC.aa.C38.3", "PC.aa.C38.4", "PC.aa.C38.5", "PC.aa.C38.6", "PC.aa.C40.5", 
          "PC.ae.C32.1", "PC.ae.C34.0", "PC.ae.C34.1", "PC.ae.C34.2", "PC.ae.C34.3", 
          "PC.ae.C36.1", "PC.ae.C36.2", "PC.ae.C36.3", "PC.ae.C36.4", "PC.ae.C36.5", 
          "PC.ae.C38.2", "PC.ae.C38.3", "PC.ae.C38.4", "PC.ae.C38.5", "PC.ae.C38.6", 
          "PC.ae.C40.2", "PC.ae.C40.5", "PC.ae.C40.6", "SM..OH..C16.1", 
          "SM..OH..C22.1", "SM..OH..C22.2", "SM..OH..C24.1", "SM.C16.0", 
          "SM.C18.0", "SM.C18.1", "SM.C20.2", "SM.C24.0", "SM.C24.1", "SM.C26.0", 
          "SM.C26.1", "TG.14.0_32.2.", "TG.14.0_34.0.", "TG.14.0_34.1.", 
          "TG.14.0_34.2.", "TG.14.0_34.3.", "TG.14.0_35.1.", "TG.14.0_35.2.", 
          "TG.14.0_36.1.", "TG.14.0_36.2.", "TG.14.0_36.3.", "TG.14.0_36.4.", 
          "TG.14.0_38.4.", "TG.14.0_38.5.", "TG.16.0_28.1.", "TG.16.0_28.2.", 
          "TG.16.0_30.2.", "TG.16.0_32.0.", "TG.16.0_32.1.", "TG.16.0_32.2.", 
          "TG.16.0_32.3.", "TG.16.0_33.1.", "TG.16.0_33.2.", "TG.16.0_34.0.", 
          "TG.16.0_34.1.", "TG.16.0_34.2.", "TG.16.0_34.3.", "TG.16.0_34.4.", 
          "TG.16.0_35.1.", "TG.16.0_35.2.", "TG.16.0_35.3.", "TG.16.0_36.2.", 
          "TG.16.0_36.3.", "TG.16.0_36.4.", "TG.16.0_36.5.", "TG.16.0_37.3.", 
          "TG.16.0_38.2.", "TG.16.0_38.3.", "TG.16.0_38.4.", "TG.16.0_38.5.", 
          "TG.16.0_38.6.", "TG.16.0_40.6.", "TG.16.1_28.0.", "TG.16.1_30.1.", 
          "TG.16.1_32.0.", "TG.16.1_32.1.", "TG.16.1_32.2.", "TG.16.1_34.0.", 
          "TG.16.1_34.1.", "TG.16.1_34.2.", "TG.16.1_34.3.", "TG.16.1_36.1.", 
          "TG.16.1_36.2.", "TG.16.1_36.3.", "TG.16.1_36.4.", "TG.16.1_36.5.", 
          "TG.16.1_38.3.", "TG.16.1_38.4.", "TG.16.1_38.5.", "TG.17.0_32.1.", 
          "TG.17.0_34.1.", "TG.17.0_34.2.", "TG.17.0_34.3.", "TG.17.0_36.3.", 
          "TG.17.0_36.4.", "TG.17.1_32.1.", "TG.17.1_34.1.", "TG.17.1_34.2.", 
          "TG.17.1_34.3.", "TG.17.1_36.3.", "TG.17.1_36.4.", "TG.18.0_30.0.", 
          "TG.18.0_30.1.", "TG.18.0_32.0.", "TG.18.0_32.1.", "TG.18.0_32.2.", 
          "TG.18.0_34.2.", "TG.18.0_34.3.", "TG.18.0_36.1.", "TG.18.0_36.2.", 
          "TG.18.0_36.3.", "TG.18.0_36.4.", "TG.18.0_36.5.", "TG.18.0_38.6.", 
          "TG.18.1_26.0.", "TG.18.1_28.1.", "TG.18.1_30.0.", "TG.18.1_30.1.", 
          "TG.18.1_30.2.", "TG.18.1_31.0.", "TG.18.1_32.0.", "TG.18.1_32.1.", 
          "TG.18.1_32.2.", "TG.18.1_32.3.", "TG.18.1_33.0.", "TG.18.1_33.1.", 
          "TG.18.1_33.2.", "TG.18.1_33.3.", "TG.18.1_34.1.", "TG.18.1_34.2.", 
          "TG.18.1_34.3.", "TG.18.1_34.4.", "TG.18.1_35.2.", "TG.18.1_35.3.", 
          "TG.18.1_36.0.", "TG.18.1_36.1.", "TG.18.1_36.2.", "TG.18.1_36.3.", 
          "TG.18.1_36.4.", "TG.18.1_36.5.", "TG.18.1_36.6.", "TG.18.1_38.5.", 
          "TG.18.1_38.6.", "TG.18.2_28.0.", "TG.18.2_30.0.", "TG.18.2_30.1.", 
          "TG.18.2_31.0.", "TG.18.2_32.0.", "TG.18.2_32.1.", "TG.18.2_32.2.", 
          "TG.18.2_33.0.", "TG.18.2_33.1.", "TG.18.2_33.2.", "TG.18.2_34.0.", 
          "TG.18.2_34.1.", "TG.18.2_34.2.", "TG.18.2_34.3.", "TG.18.2_34.4.", 
          "TG.18.2_35.1.", "TG.18.2_35.2.", "TG.18.2_35.3.", "TG.18.2_36.0.", 
          "TG.18.2_36.1.", "TG.18.2_36.2.", "TG.18.2_36.3.", "TG.18.2_36.4.", 
          "TG.18.2_36.5.", "TG.18.2_38.4.", "TG.18.2_38.5.", "TG.18.2_38.6.", 
          "TG.18.3_30.0.", "TG.18.3_32.0.", "TG.18.3_32.1.", "TG.18.3_33.2.", 
          "TG.18.3_34.0.", "TG.18.3_34.1.", "TG.18.3_34.2.", "TG.18.3_34.3.", 
          "TG.18.3_35.2.", "TG.18.3_36.1.", "TG.18.3_36.2.", "TG.18.3_36.3.", 
          "TG.18.3_36.4.", "TG.20.0_32.3.", "TG.20.0_32.4.", "TG.20.1_30.1.", 
          "TG.20.1_32.1.", "TG.20.1_32.2.", "TG.20.1_32.3.", "TG.20.1_34.2.", 
          "TG.20.1_34.3.", "TG.20.2_32.0.", "TG.20.2_32.1.", "TG.20.2_34.1.", 
          "TG.20.2_34.2.", "TG.20.2_34.3.", "TG.20.3_32.0.", "TG.20.3_32.1.", 
          "TG.20.3_32.2.", "TG.20.3_34.0.", "TG.20.3_34.1.", "TG.20.3_34.2.", 
          "TG.20.3_34.3.", "TG.20.3_36.3.", "TG.20.3_36.4.", "TG.20.4_30.0.", 
          "TG.20.4_32.0.", "TG.20.4_32.1.", "TG.20.4_32.2.", "TG.20.4_33.2.", 
          "TG.20.4_34.0.", "TG.20.4_34.1.", "TG.20.4_34.2.", "TG.20.4_34.3.", 
          "TG.20.4_36.2.", "TG.20.4_36.3.", "TG.20.4_36.4.", "TG.20.5_34.0.", 
          "TG.20.5_34.1.", "TG.22.4_32.0.", "TG.22.4_32.2.", "TG.22.5_32.1.", 
          "TG.22.5_34.1.", "TG.22.6_32.1.", "TG.22.6_34.1.", "TG.22.6_34.2.", 
          "Choline")
outcome = "haz_6m_simulated"

slModelFunc(bioc, covars = covars, outcome = outcome)
```

# Data in the long format
```{r}

```

