---
title: |
  Heatmaps and Clusters
author: "Sajia Darwish"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
---

# Load libraries
```{r}
library(pheatmap)
library(dendextend)
library(caret)
```

# Make a function to choose a given number of most variant features + plot heatmap
```{r}
select_and_plot_top_features <- function(data, n_features = 60, file_name) {
  
  # Compute standard deviation for each feature
  standard_deviation <- sapply(data, sd, na.rm = TRUE)
  
  # Sort features by standard deviation in descending order
  sorted_features <- sort(standard_deviation, decreasing = TRUE)
  
  # Select the top n_features most variable features
  top_features <- names(sorted_features)[1:n_features]
  
  # Subset the original data frame to only include the top n_features most variable features
  subset_data <- data %>% select(all_of(top_features))
  
  # Convert the subsetted data frame to a matrix
  dataMatrix <- as.matrix(subset_data)
  
  
  # Set up file path for image to save
  png(file = file_name, width = 700, height = 520)
  
  # Create and return the pheatmap plot
  pheatmap(dataMatrix)
  
  dev.off()
}
```

# Load data from elicit
```{r}
hmoE <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/hmoClean.RDS")
hmoE <- hmoE %>%
  select(c("X2.FL", "X3FL", "DFLac", 
          "X3.SL", "X6.SL", "LNT", "LNnT", "LNFP.I", "LNFP.II", "LNFP.III", 
          "LSTb", "LSTc", "DFLNT", "LNH", "DSLNT", "FLNH", "DFLNH", "FDSLNH", 
          "DSLNH", "SUM", "Sia", "Fuc")) %>%
    drop_na()

biocNormE <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/biocNormClean.RDS")
biocNormE <- biocNormE %>%
  select(!c("bmid_base", "country", "studyid", "subjid", "subjido", "arm_base", 
          "sex_base", "brthyr_base", "brthweek_base", "mage_base", "parity_base", 
          "nlchild_base", "nperson_base", "nrooms_base", "meducyrs_base", 
          "h2osrcp_base", "cookplac_base", "inctot_base", "inctotu_base", 
          "epoch_base", "mhtcm_base", "mwtkg_base", "mbmi_base", "dlvloc_base", 
          "dvseason_base", "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", 
          "waz_base", "haz_base", "whz_base", "baz_base", "agedays_base", 
          "dur_bf_base", "dur_ebf_base", "lencm_3m", "lencm_6m", "lencm_9m", 
          "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
          "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
          "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
          "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", "haz_6m", 
          "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
          "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
          "baz_9m", "baz_12m", "baz_15m", "baz_18m", "exbfdu_r_0to6m", 
          "fever_r_0to6m", "fever_r_6to18m", "cough_r_0to6m", "cough_r_6to18m", 
          "diarr_r_0to6m", "diarr_r_6to18m", "mhgb_18m", "muaccm_18m", 
          "muaz_18m", "bfdu_r_0to18m", "anti_r_0to18m", "haz_6m_simulated", 
          "family")) %>%
    drop_na()

bvitE <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/bvitClean.RDS")
#dput(names(bvitE))
bvitE <- bvitE %>%
  select(c("B12", "TPP", "TMP", "T", "B1", "Ribo", "FMN", 
          "FAD", "NAM", "NAD", "NMN", "NR", "Nufa", "PA", "PL", "PM", "PN", 
          "PLP", "Bio", "TRP", "B2", "B3", "B6")) %>%
    drop_na()

metabolE <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/metabolClean.RDS")
#dput(names(metabolE))
metabolE <- metabolE %>%
  select(!c("bmid_base", "country", "studyid", "siteid", "subjid", "subjido", 
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "inctot_base", 
            "inctotu_base", "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", 
            "mbmi_base", "pregout_base", "dlvloc_base", "dvseason_base", 
            "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", "waz_base", 
            "haz_base", "whz_base", "baz_base", "agedays_base", "feeding_base", 
            "dur_bf_base", "dur_ebf_base", "bmcol_fl_1m", "bmcol_fl_5m", 
            "agedays_1m", "agedays_5m", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", "haz_6m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "agedays_3m", "agedays_6m", 
            "agedays_9m", "agedays_12m", "agedays_15m", "agedays_18m", "visit_r_fl_0to6m", 
            "visit_r_fl_6to18m", "dur_r_0to6m", "dur_r_6to18m", "bfedfl_r_0to6m", 
            "exbfed_r_0to6m", "exbfdu_r_0to6m", "fever_r_0to6m", "fever_r_6to18m", 
            "cough_r_0to6m", "cough_r_6to18m", "diarr_r_0to6m", "diarr_r_6to18m", 
            "mhgb_18m", "muaccm_18m", "muaz_18m", "agedays_18m.1", "bfdu_r_0to18m", 
            "anti_r_0to18m", "haz_6m_simulated", "family")) %>%
    drop_na()

# Cut names to 10 characters
#colnames(metabolE) <- substr(colnames(metabolE), 1, 10)

sapientE <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/sapientClean.RDS")
#dput(names(sapient)[60700:60722])
sapientE <- sapientE %>%
  select(!c("bmid_base", "country", "studyid", "siteid", "subjid", "subjido", 
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "inctot_base", 
            "inctotu_base", "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", 
            "mbmi_base", "pregout_base", "dlvloc_base", "dvseason_base", 
            "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", "waz_base", 
            "haz_base", "whz_base", "baz_base", "agedays_base", "feeding_base", 
            "dur_bf_base", "dur_ebf_base", "bmcol_fl_1m", "bmcol_fl_5m", 
            "agedays_1m", "agedays_5m", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", "haz_6m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "agedays_3m", "agedays_6m", 
            "agedays_9m", "agedays_12m", "agedays_15m", "agedays_18m", "visit_r_fl_0to6m", 
            "visit_r_fl_6to18m", "dur_r_0to6m", "dur_r_6to18m", "bfedfl_r_0to6m", 
            "exbfed_r_0to6m", "exbfdu_r_0to6m", "fever_r_0to6m", "fever_r_6to18m", 
            "cough_r_0to6m", "cough_r_6to18m", "diarr_r_0to6m", "diarr_r_6to18m", 
            "mhgb_18m", "muaccm_18m", "muaz_18m", "agedays_18m.1", "bfdu_r_0to18m", 
            "anti_r_0to18m", "haz_6m_simulated", "family"))

# Replace NAs with a small number
sapientE[is.na(sapientE)] <- 0.00001
```

# Load data from vital
```{r}
hmoV <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/hmoClean.RDS")
dput(names(hmoV))
hmoV <- hmoV %>%
  select(c("X2.FL_nmol.mL", "X3FL_nmol.mL", "DFLac_nmol.mL", 
            "X3.SL_nmol.mL", "X6.SL_nmol.mL", "LNT_nmol.mL", "LNnT_nmol.mL", 
            "LNFP.I_nmol.mL", "LNFP.II_nmol.mL", "LNFP.III_nmol.mL", "LSTb_nmol.mL", 
            "LSTc_nmol.mL", "DFLNT_nmol.mL", "LNH_nmol.mL", "DSLNT_nmol.mL", 
            "FLNH_nmol.mL", "DFLNH_nmol.mL", "FDSLNH_nmol.mL", "DSLNH_nmol.mL", 
            "SUM_nmol.mL", "Sia_nmol.mL", "Fuc_nmol.mL")) %>%
    drop_na()

# Shorten names
# Drop everything after "_2022" in column names
colnames(hmoV) <- gsub("_.*", "", colnames(hmoV))

biocNormV <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/biocNormClean.RDS")
#dput(names(biocNormV))
biocNormV <- biocNormV %>%
  select(!c("bmid_base", "subjid", "country", "studyid", "subjido", "arm_base", 
            "sex_base", "brthyr_base", "brthweek_base", "mage_base", "parity_base", 
            "nlchild_base", "nperson_base", "nrooms_base", "meducyrs_base", 
            "h2osrcp_base", "agedays_base", "epochn_base", "epoch_base", 
            "mhtcm_base", "mwtkg_base", "mbmi_base", "dlvloc_base", "wtkg_base", 
            "lencm_base", "bmi_base", "muaccm_base", "waz_base", "haz_base", 
            "whz_base", "baz_base", "feeding_base", "dur_bf_base", "dur_ebf_base", 
            "visit_r_fl_base", "dur_r_base", "fever_r_base", "cough_r_base", 
            "anti_r_base", "citytown_base", "gagebrth_base", "gagecm_base", 
            "birthwt_base", "birthlen_base", "birthord_base", "gravida_base", 
            "nlivbrth_base", "floor_base", "gagedays_base", "postbmi_base", 
            "mmuaccm_base", "delivery_base", "bfinittm_base", "cmfdint_base", 
            "formlkfl_base", "fever_base", "diarr_base", "physican_base", 
            "hosp_base", "antibiot_base", "anti_oral_base", "anti_inj_base", 
            "agedays_m1", "mhtcm_m1", "mwtkg_m1", "mbmi_m1", "wtkg_m1", "lencm_m1", 
            "bmi_m1", "muaccm_m1", "waz_m1", "haz_m1", "whz_m1", "baz_m1", 
            "feeding_m1", "dur_bf_m1", "dur_ebf_m1", "visit_r_fl_m1", "dur_r_m1", 
            "fever_r_m1", "cough_r_m1", "anti_r_m1", "gagedays_m1", "postbmi_m1", 
            "mmuaccm_m1", "cmfdint_m1", "bfmode_m1", "bfedfl_m1", "exbfedfl_m1", 
            "sldfedfl_m1", "cough_m1", "physican_m1", "hosp_m1", "antibiot_m1", 
            "anti_oral_m1", "anti_inj_m1", "agedays_m2", "mhtcm_m2", "mwtkg_m2", 
            "mbmi_m2", "mhgb_m2", "wtkg_m2", "lencm_m2", "bmi_m2", "muaccm_m2", 
            "waz_m2", "haz_m2", "whz_m2", "baz_m2", "feeding_m2", "dur_bf_m2", 
            "dur_ebf_m2", "visit_r_fl_m2", "dur_r_m2", "cough_r_m2", "anti_r_m2", 
            "gagedays_m2", "postbmi_m2", "mmuaccm_m2", "hgb_m2", "cmfdint_m2", 
            "bfmode_m2", "bfedfl_m2", "exbfedfl_m2", "cough_m2", "physican_m2", 
            "hosp_m2", "antibiot_m2", "anti_oral_m2", "anti_inj_m2", "mcrp_m2", 
            "mferritin_m2", "mstrf_m2", "magp_m2", "agedays_m3", "mhtcm_m3", 
            "mwtkg_m3", "mbmi_m3", "wtkg_m3", "lencm_m3", "bmi_m3", "muaccm_m3", 
            "waz_m3", "haz_m3", "whz_m3", "baz_m3", "muaz_m3", "feeding_m3", 
            "dur_bf_m3", "dur_ebf_m3", "visit_r_fl_m3", "dur_r_m3", "fever_r_m3", 
            "cough_r_m3", "anti_r_m3", "gagedays_m3", "postbmi_m3", "mmuaccm_m3", 
            "cmfdint_m3", "bfmode_m3", "bfedfl_m3", "exbfedfl_m3", "fever_m3", 
            "cough_m3", "diarr_m3", "physican_m3", "antibiot_m3", "anti_oral_m3", 
            "anti_inj_m3", "agedays_m4", "mhtcm_m4", "mwtkg_m4", "mbmi_m4", 
            "wtkg_m4", "lencm_m4", "bmi_m4", "muaccm_m4", "waz_m4", "haz_m4", 
            "whz_m4", "baz_m4", "muaz_m4", "feeding_m4", "dur_bf_m4", "dur_ebf_m4", 
            "visit_r_fl_m4", "dur_r_m4", "cough_r_m4", "anti_r_m4", "gagedays_m4", 
            "postbmi_m4", "mmuaccm_m4", "cmfdint_m4", "bfmode_m4", "bfedfl_m4", 
            "exbfedfl_m4", "fever_m4", "cough_m4", "vomit_m4", "physican_m4", 
            "hosp_m4", "antibiot_m4", "anti_oral_m4", "anti_inj_m4", "agedays_m5", 
            "mhtcm_m5", "mwtkg_m5", "mbmi_m5", "wtkg_m5", "lencm_m5", "bmi_m5", 
            "muaccm_m5", "waz_m5", "haz_m5", "whz_m5", "baz_m5", "muaz_m5", 
            "feeding_m5", "dur_bf_m5", "dur_ebf_m5", "visit_r_fl_m5", "dur_r_m5", 
            "fever_r_m5", "cough_r_m5", "diarr_r_m5", "anti_r_m5", "gagedays_m5", 
            "postbmi_m5", "mmuaccm_m5", "cmfdint_m5", "bfmode_m5", "bfedfl_m5", 
            "exbfedfl_m5", "sldfedfl_m5", "fever_m5", "cough_m5", "diarr_m5", 
            "physican_m5", "antibiot_m5", "anti_oral_m5", "anti_inj_m5", 
            "agedays_m6", "mhtcm_m6", "mwtkg_m6", "mbmi_m6", "wtkg_m6", "lencm_m6", 
            "bmi_m6", "muaccm_m6", "waz_m6", "haz_m6", "whz_m6", "baz_m6", 
            "muaz_m6", "feeding_m6", "dur_bf_m6", "dur_ebf_m6", "visit_r_fl_m6", 
            "dur_r_m6", "cough_r_m6", "diarr_r_m6", "anti_r_m6", "gagedays_m6", 
            "postbmi_m6", "mmuaccm_m6", "cmfdint_m6", "bfmode_m6", "bfedfl_m6", 
            "exbfedfl_m6", "sldfedfl_m6", "cough_m6", "diarr_m6", "physican_m6", 
            "hosp_m6", "antibiot_m6", "anti_oral_m6", "anti_inj_m6", "haz_6m_simulated", "family")) %>%
    drop_na()

pblV <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/pblClean.RDS")
dput(names(pblV)[1:400])
pblV <- pblV %>%
  select(!c("bmid_base", "subjid", "country", "studyid", "siteid", "subjido", 
          "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
          "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
          "meducyrs_base", "h2osrcp_base", "cookplac_base", "agedays_base", 
          "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", "mbmi_base", 
          "pregout_base", "dlvloc_base", "wtkg_base", "lencm_base", "bmi_base", 
          "muaccm_base", "waz_base", "haz_base", "whz_base", "baz_base", 
          "feeding_base", "dur_bf_base", "dur_ebf_base", "visit_r_fl_base", 
          "dur_r_base", "fever_r_base", "cough_r_base", "anti_r_base", 
          "citytown_base", "gagebrth_base", "gagecm_base", "birthwt_base", 
          "birthlen_base", "birthord_base", "gravida_base", "nlivbrth_base", 
          "floor_base", "gagedays_base", "postbmi_base", "mmuaccm_base", 
          "delivery_base", "bfinittm_base", "cmfdint_base", "exbfedfl_base", 
          "formlkfl_base", "fever_base", "cough_base", "diarr_base", "vomit_base", 
          "physican_base", "hosp_base", "antibiot_base", "anti_oral_base", 
          "anti_inj_base", "agedays_m1", "mhtcm_m1", "mwtkg_m1", "mbmi_m1", 
          "wtkg_m1", "lencm_m1", "bmi_m1", "muaccm_m1", "waz_m1", "haz_m1", 
          "whz_m1", "baz_m1", "feeding_m1", "dur_bf_m1", "dur_ebf_m1", 
          "visit_r_fl_m1", "dur_r_m1", "fever_r_m1", "cough_r_m1", "diarr_r_m1", 
          "anti_r_m1", "gagedays_m1", "postbmi_m1", "mmuaccm_m1", "cmfdint_m1", 
          "bfmode_m1", "bfedfl_m1", "exbfedfl_m1", "sldfedfl_m1", "fever_m1", 
          "cough_m1", "diarr_m1", "vomit_m1", "physican_m1", "hosp_m1", 
          "antibiot_m1", "anti_oral_m1", "anti_inj_m1", "agedays_m2", "mhtcm_m2", 
          "mwtkg_m2", "mbmi_m2", "mhgb_m2", "wtkg_m2", "lencm_m2", "bmi_m2", 
          "muaccm_m2", "waz_m2", "haz_m2", "whz_m2", "baz_m2", "feeding_m2", 
          "dur_bf_m2", "dur_ebf_m2", "visit_r_fl_m2", "dur_r_m2", "fever_r_m2", 
          "cough_r_m2", "diarr_r_m2", "anti_r_m2", "gagedays_m2", "postbmi_m2", 
          "mmuaccm_m2", "hgb_m2", "cmfdint_m2", "bfmode_m2", "bfedfl_m2", 
          "exbfedfl_m2", "sldfedfl_m2", "fever_m2", "cough_m2", "diarr_m2", 
          "vomit_m2", "physican_m2", "hosp_m2", "antibiot_m2", "anti_oral_m2", 
          "anti_inj_m2", "mcrp_m2", "mferritin_m2", "mstrf_m2", "magp_m2", 
          "agedays_m3", "mhtcm_m3", "mwtkg_m3", "mbmi_m3", "wtkg_m3", "lencm_m3", 
          "bmi_m3", "muaccm_m3", "waz_m3", "haz_m3", "whz_m3", "baz_m3", 
          "muaz_m3", "feeding_m3", "dur_bf_m3", "dur_ebf_m3", "visit_r_fl_m3", 
          "dur_r_m3", "fever_r_m3", "cough_r_m3", "diarr_r_m3", "anti_r_m3", 
          "gagedays_m3", "postbmi_m3", "mmuaccm_m3", "cmfdint_m3", "bfmode_m3", 
          "bfedfl_m3", "exbfedfl_m3", "sldfedfl_m3", "fever_m3", "cough_m3", 
          "diarr_m3", "vomit_m3", "physican_m3", "hosp_m3", "antibiot_m3", 
          "anti_oral_m3", "anti_inj_m3", "agedays_m4", "mhtcm_m4", "mwtkg_m4", 
          "mbmi_m4", "wtkg_m4", "lencm_m4", "bmi_m4", "muaccm_m4", "waz_m4", 
          "haz_m4", "whz_m4", "baz_m4", "muaz_m4", "feeding_m4", "dur_bf_m4", 
          "dur_ebf_m4", "visit_r_fl_m4", "dur_r_m4", "fever_r_m4", "cough_r_m4", 
          "diarr_r_m4", "anti_r_m4", "gagedays_m4", "postbmi_m4", "mmuaccm_m4", 
          "cmfdint_m4", "bfmode_m4", "bfedfl_m4", "exbfedfl_m4", "sldfedfl_m4", 
          "fever_m4", "cough_m4", "diarr_m4", "vomit_m4", "physican_m4", 
          "hosp_m4", "antibiot_m4", "anti_oral_m4", "anti_inj_m4", "agedays_m5", 
          "mhtcm_m5", "mwtkg_m5", "mbmi_m5", "wtkg_m5", "lencm_m5", "bmi_m5", 
          "muaccm_m5", "waz_m5", "haz_m5", "whz_m5", "baz_m5", "muaz_m5", 
          "feeding_m5", "dur_bf_m5", "dur_ebf_m5", "visit_r_fl_m5", "dur_r_m5", 
          "fever_r_m5", "cough_r_m5", "diarr_r_m5", "anti_r_m5", "gagedays_m5", 
          "postbmi_m5", "mmuaccm_m5", "cmfdint_m5", "bfmode_m5", "bfedfl_m5", 
          "exbfedfl_m5", "sldfedfl_m5", "fever_m5", "cough_m5", "diarr_m5", 
          "vomit_m5", "physican_m5", "hosp_m5", "antibiot_m5", "anti_oral_m5", 
          "anti_inj_m5", "agedays_m6", "mhtcm_m6", "mwtkg_m6", "mbmi_m6", 
          "wtkg_m6", "lencm_m6", "bmi_m6", "muaccm_m6", "waz_m6", "haz_m6", 
          "whz_m6", "baz_m6", "muaz_m6", "feeding_m6", "dur_bf_m6", "dur_ebf_m6", 
          "visit_r_fl_m6", "dur_r_m6", "fever_r_m6", "cough_r_m6", "diarr_r_m6", 
          "anti_r_m6", "gagedays_m6", "postbmi_m6", "mmuaccm_m6", "cmfdint_m6", 
          "bfmode_m6", "bfedfl_m6", "exbfedfl_m6", "sldfedfl_m6", "fever_m6", 
          "cough_m6", "diarr_m6", "vomit_m6", "physican_m6", "hosp_m6", 
          "antibiot_m6", "anti_oral_m6", "anti_inj_m6",  "haz_6m_simulated", "family")) %>%
    drop_na()

metabolV <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/metabolClean.RDS")
dput(names(metabolV))
metabolV <- metabolV %>%
  select(!c("bmid_base", "subjid", "country", "studyid", "siteid", "subjido", 
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "agedays_base", 
            "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", "mbmi_base", 
            "pregout_base", "dlvloc_base", "wtkg_base", "lencm_base", "bmi_base", 
            "muaccm_base", "waz_base", "haz_base", "whz_base", "baz_base", 
            "feeding_base", "dur_bf_base", "dur_ebf_base", "visit_r_fl_base", 
            "dur_r_base", "fever_r_base", "cough_r_base", "anti_r_base", 
            "citytown_base", "gagebrth_base", "gagecm_base", "birthwt_base", 
            "birthlen_base", "birthord_base", "gravida_base", "nlivbrth_base", 
            "floor_base", "gagedays_base", "postbmi_base", "mmuaccm_base", 
            "delivery_base", "bfinittm_base", "cmfdint_base", "exbfedfl_base", 
            "formlkfl_base", "fever_base", "cough_base", "diarr_base", "vomit_base", 
            "physican_base", "hosp_base", "antibiot_base", "anti_oral_base", 
            "anti_inj_base", "agedays_m1", "mhtcm_m1", "mwtkg_m1", "mbmi_m1", 
            "wtkg_m1", "lencm_m1", "bmi_m1", "muaccm_m1", "waz_m1", "haz_m1", 
            "whz_m1", "baz_m1", "feeding_m1", "dur_bf_m1", "dur_ebf_m1", 
            "visit_r_fl_m1", "dur_r_m1", "fever_r_m1", "cough_r_m1", "diarr_r_m1", 
            "anti_r_m1", "gagedays_m1", "postbmi_m1", "mmuaccm_m1", "cmfdint_m1", 
            "bfmode_m1", "bfedfl_m1", "exbfedfl_m1", "sldfedfl_m1", "fever_m1", 
            "cough_m1", "diarr_m1", "vomit_m1", "physican_m1", "hosp_m1", 
            "antibiot_m1", "anti_oral_m1", "anti_inj_m1", "agedays_m2", "mhtcm_m2", 
            "mwtkg_m2", "mbmi_m2", "mhgb_m2", "wtkg_m2", "lencm_m2", "bmi_m2", 
            "muaccm_m2", "waz_m2", "haz_m2", "whz_m2", "baz_m2", "feeding_m2", 
            "dur_bf_m2", "dur_ebf_m2", "visit_r_fl_m2", "dur_r_m2", "fever_r_m2", 
            "cough_r_m2", "diarr_r_m2", "anti_r_m2", "gagedays_m2", "postbmi_m2", 
            "mmuaccm_m2", "hgb_m2", "cmfdint_m2", "bfmode_m2", "bfedfl_m2", 
            "exbfedfl_m2", "sldfedfl_m2", "fever_m2", "cough_m2", "diarr_m2", 
            "vomit_m2", "physican_m2", "hosp_m2", "antibiot_m2", "anti_oral_m2", 
            "anti_inj_m2", "mcrp_m2", "mferritin_m2", "mstrf_m2", "magp_m2", 
            "agedays_m3", "mhtcm_m3", "mwtkg_m3", "mbmi_m3", "wtkg_m3", "lencm_m3", 
            "bmi_m3", "muaccm_m3", "waz_m3", "haz_m3", "whz_m3", "baz_m3", 
            "muaz_m3", "feeding_m3", "dur_bf_m3", "dur_ebf_m3", "visit_r_fl_m3", 
            "dur_r_m3", "fever_r_m3", "cough_r_m3", "diarr_r_m3", "anti_r_m3", 
            "gagedays_m3", "postbmi_m3", "mmuaccm_m3", "cmfdint_m3", "bfmode_m3", 
            "bfedfl_m3", "exbfedfl_m3", "sldfedfl_m3", "fever_m3", "cough_m3", 
            "diarr_m3", "vomit_m3", "physican_m3", "hosp_m3", "antibiot_m3", 
            "anti_oral_m3", "anti_inj_m3", "agedays_m4", "mhtcm_m4", "mwtkg_m4", 
            "mbmi_m4", "wtkg_m4", "lencm_m4", "bmi_m4", "muaccm_m4", "waz_m4", 
            "haz_m4", "whz_m4", "baz_m4", "muaz_m4", "feeding_m4", "dur_bf_m4", 
            "dur_ebf_m4", "visit_r_fl_m4", "dur_r_m4", "fever_r_m4", "cough_r_m4", 
            "diarr_r_m4", "anti_r_m4", "gagedays_m4", "postbmi_m4", "mmuaccm_m4", 
            "cmfdint_m4", "bfmode_m4", "bfedfl_m4", "exbfedfl_m4", "sldfedfl_m4", 
            "fever_m4", "cough_m4", "diarr_m4", "vomit_m4", "physican_m4", 
            "hosp_m4", "antibiot_m4", "anti_oral_m4", "anti_inj_m4", "agedays_m5", 
            "mhtcm_m5", "mwtkg_m5", "mbmi_m5", "wtkg_m5", "lencm_m5", "bmi_m5", 
            "muaccm_m5", "waz_m5", "haz_m5", "whz_m5", "baz_m5", "muaz_m5", 
            "feeding_m5", "dur_bf_m5", "dur_ebf_m5", "visit_r_fl_m5", "dur_r_m5", 
            "fever_r_m5", "cough_r_m5", "diarr_r_m5", "anti_r_m5", "gagedays_m5", 
            "postbmi_m5", "mmuaccm_m5", "cmfdint_m5", "bfmode_m5", "bfedfl_m5", 
            "exbfedfl_m5", "sldfedfl_m5", "fever_m5", "cough_m5", "diarr_m5", 
            "vomit_m5", "physican_m5", "hosp_m5", "antibiot_m5", "anti_oral_m5", 
            "anti_inj_m5", "agedays_m6", "mhtcm_m6", "mwtkg_m6", "mbmi_m6", 
            "wtkg_m6", "lencm_m6", "bmi_m6", "muaccm_m6", "waz_m6", "haz_m6", 
            "whz_m6", "baz_m6", "muaz_m6", "feeding_m6", "dur_bf_m6", "dur_ebf_m6", 
            "visit_r_fl_m6", "dur_r_m6", "fever_r_m6", "cough_r_m6", "diarr_r_m6", 
            "anti_r_m6", "gagedays_m6", "postbmi_m6", "mmuaccm_m6", "cmfdint_m6", 
            "bfmode_m6", "bfedfl_m6", "exbfedfl_m6", "sldfedfl_m6", "fever_m6", 
            "cough_m6", "diarr_m6", "vomit_m6", "physican_m6", "hosp_m6", 
            "antibiot_m6", "anti_oral_m6", "anti_inj_m6", "haz_6m_simulated", "family")) %>%
    drop_na()

# Cut names to 10 characters
#colnames(metabolV) <- substr(colnames(metabolV), 1, 10)

sapientV <- readRDS("/data/imic/data/raw_lab_data/vital/merged_vital/sapientClean.RDS")
dput(names(sapientV)[1:500])
sapientV <- sapientV %>%
  select(!c("bmid_base", "subjid", "country", "studyid", "siteid", "subjido", 
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "agedays_base", 
            "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", "mbmi_base", 
            "pregout_base", "dlvloc_base", "wtkg_base", "lencm_base", "bmi_base", 
            "muaccm_base", "waz_base", "haz_base", "whz_base", "baz_base", 
            "feeding_base", "dur_bf_base", "dur_ebf_base", "visit_r_fl_base", 
            "dur_r_base", "fever_r_base", "cough_r_base", "anti_r_base", 
            "citytown_base", "gagebrth_base", "gagecm_base", "birthwt_base", 
            "birthlen_base", "birthord_base", "gravida_base", "nlivbrth_base", 
            "floor_base", "gagedays_base", "postbmi_base", "mmuaccm_base", 
            "delivery_base", "bfinittm_base", "cmfdint_base", "exbfedfl_base", 
            "formlkfl_base", "fever_base", "cough_base", "diarr_base", "vomit_base", 
            "physican_base", "hosp_base", "antibiot_base", "anti_oral_base", 
            "anti_inj_base", "agedays_m1", "mhtcm_m1", "mwtkg_m1", "mbmi_m1", 
            "wtkg_m1", "lencm_m1", "bmi_m1", "muaccm_m1", "waz_m1", "haz_m1", 
            "whz_m1", "baz_m1", "feeding_m1", "dur_bf_m1", "dur_ebf_m1", 
            "visit_r_fl_m1", "dur_r_m1", "fever_r_m1", "cough_r_m1", "diarr_r_m1", 
            "anti_r_m1", "gagedays_m1", "postbmi_m1", "mmuaccm_m1", "cmfdint_m1", 
            "bfmode_m1", "bfedfl_m1", "exbfedfl_m1", "sldfedfl_m1", "fever_m1", 
            "cough_m1", "diarr_m1", "vomit_m1", "physican_m1", "hosp_m1", 
            "antibiot_m1", "anti_oral_m1", "anti_inj_m1", "agedays_m2", "mhtcm_m2", 
            "mwtkg_m2", "mbmi_m2", "mhgb_m2", "wtkg_m2", "lencm_m2", "bmi_m2", 
            "muaccm_m2", "waz_m2", "haz_m2", "whz_m2", "baz_m2", "feeding_m2", 
            "dur_bf_m2", "dur_ebf_m2", "visit_r_fl_m2", "dur_r_m2", "fever_r_m2", 
            "cough_r_m2", "diarr_r_m2", "anti_r_m2", "gagedays_m2", "postbmi_m2", 
            "mmuaccm_m2", "hgb_m2", "cmfdint_m2", "bfmode_m2", "bfedfl_m2", 
            "exbfedfl_m2", "sldfedfl_m2", "fever_m2", "cough_m2", "diarr_m2", 
            "vomit_m2", "physican_m2", "hosp_m2", "antibiot_m2", "anti_oral_m2", 
            "anti_inj_m2", "mcrp_m2", "mferritin_m2", "mstrf_m2", "magp_m2", 
            "agedays_m3", "mhtcm_m3", "mwtkg_m3", "mbmi_m3", "wtkg_m3", "lencm_m3", 
            "bmi_m3", "muaccm_m3", "waz_m3", "haz_m3", "whz_m3", "baz_m3", 
            "muaz_m3", "feeding_m3", "dur_bf_m3", "dur_ebf_m3", "visit_r_fl_m3", 
            "dur_r_m3", "fever_r_m3", "cough_r_m3", "diarr_r_m3", "anti_r_m3", 
            "gagedays_m3", "postbmi_m3", "mmuaccm_m3", "cmfdint_m3", "bfmode_m3", 
            "bfedfl_m3", "exbfedfl_m3", "sldfedfl_m3", "fever_m3", "cough_m3", 
            "diarr_m3", "vomit_m3", "physican_m3", "hosp_m3", "antibiot_m3", 
            "anti_oral_m3", "anti_inj_m3", "agedays_m4", "mhtcm_m4", "mwtkg_m4", 
            "mbmi_m4", "wtkg_m4", "lencm_m4", "bmi_m4", "muaccm_m4", "waz_m4", 
            "haz_m4", "whz_m4", "baz_m4", "muaz_m4", "feeding_m4", "dur_bf_m4", 
            "dur_ebf_m4", "visit_r_fl_m4", "dur_r_m4", "fever_r_m4", "cough_r_m4", 
            "diarr_r_m4", "anti_r_m4", "gagedays_m4", "postbmi_m4", "mmuaccm_m4", 
            "cmfdint_m4", "bfmode_m4", "bfedfl_m4", "exbfedfl_m4", "sldfedfl_m4", 
            "fever_m4", "cough_m4", "diarr_m4", "vomit_m4", "physican_m4", 
            "hosp_m4", "antibiot_m4", "anti_oral_m4", "anti_inj_m4", "agedays_m5", 
            "mhtcm_m5", "mwtkg_m5", "mbmi_m5", "wtkg_m5", "lencm_m5", "bmi_m5", 
            "muaccm_m5", "waz_m5", "haz_m5", "whz_m5", "baz_m5", "muaz_m5", 
            "feeding_m5", "dur_bf_m5", "dur_ebf_m5", "visit_r_fl_m5", "dur_r_m5", 
            "fever_r_m5", "cough_r_m5", "diarr_r_m5", "anti_r_m5", "gagedays_m5", 
            "postbmi_m5", "mmuaccm_m5", "cmfdint_m5", "bfmode_m5", "bfedfl_m5", 
            "exbfedfl_m5", "sldfedfl_m5", "fever_m5", "cough_m5", "diarr_m5", 
            "vomit_m5", "physican_m5", "hosp_m5", "antibiot_m5", "anti_oral_m5", 
            "anti_inj_m5", "agedays_m6", "mhtcm_m6", "mwtkg_m6", "mbmi_m6", 
            "wtkg_m6", "lencm_m6", "bmi_m6", "muaccm_m6", "waz_m6", "haz_m6", 
            "whz_m6", "baz_m6", "muaz_m6", "feeding_m6", "dur_bf_m6", "dur_ebf_m6", 
            "visit_r_fl_m6", "dur_r_m6", "fever_r_m6", "cough_r_m6", "diarr_r_m6", 
            "anti_r_m6", "gagedays_m6", "postbmi_m6", "mmuaccm_m6", "cmfdint_m6", 
            "bfmode_m6", "bfedfl_m6", "exbfedfl_m6", "sldfedfl_m6", "fever_m6", 
            "cough_m6", "diarr_m6", "vomit_m6", "physican_m6", "hosp_m6", 
            "antibiot_m6", "anti_oral_m6", "anti_inj_m6", "haz_6m_simulated", "family"))

# Replace NAs with a small number
sapientV[is.na(sapientV)] <- 0.00001
```

# Call the function on elicit data
```{r}
select_and_plot_top_features(hmoE, n_features = 22, 
                             file_name = "/data/imic/results/figures/heatmaps/hmoE.png")
select_and_plot_top_features(biocNormE, n_features = 60, 
                             file_name = "/data/imic/results/figures/heatmaps/biocNormE.png")
select_and_plot_top_features(bvitE, n_features = 23, 
                             file_name = "/data/imic/results/figures/heatmaps/bvitE.png")
select_and_plot_top_features(metabolE, n_features = 60, 
                             file_name = "/data/imic/results/figures/heatmaps/metabolE.png")
select_and_plot_top_features(sapientE, n_features = 60, 
                             file_name = "/data/imic/results/figures/heatmaps/sapientE.png")
```

# Call the function on vital data
```{r}
select_and_plot_top_features(hmoV, n_features = 22, 
                             file_name = "/data/imic/results/figures/heatmaps/hmoV.png")
select_and_plot_top_features(biocNormV, n_features = 60, 
                             file_name = "/data/imic/results/figures/heatmaps/biocNormV.png")
select_and_plot_top_features(pblV, n_features = 60, 
                             file_name = "/data/imic/results/figures/heatmaps/pblV.png")
select_and_plot_top_features(metabolV, n_features = 60, 
                             file_name = "/data/imic/results/figures/heatmaps/metabolV.png")
select_and_plot_top_features(sapientV, n_features = 60, 
                             file_name = "/data/imic/results/figures/heatmaps/sapientV.png")
```













