---
title: |
  TMLE Parallelization
author: "Sajia Darwish"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
---

```{r, include=FALSE}
#rm(list=ls())
#source(paste0(here::here(), "/0-config.R"))
library(tidyverse)
library(sl3)
library(tmle3)
library(tidyverse)
library(foreach)
library(parallel)
library(doParallel)
registerDoParallel(cores=50)
library(Rsolnp)
library(dplyr)
```

# Make a TMLE function and a table function
```{r, include=FALSE}
tmleFunc <- function(W, A, Y, data) {
  # Define the variable roles
  node_list <- list(W = W, A = A, Y = Y)

  processed <- process_missing(data, node_list)
  data2 <- processed $ data # Remember that now data is data2 now.
  node_list <- processed $ node_list

  # Dichotomize A
  for (i in 1:nrow(data2)) {
    data2[[A]][i] <- ifelse(data2[[A]][i] > median(data2[[A]]), 1, 0)
  }

  ate_spec <- tmle_ATE(treatment_level = 1, control_level = 0)

  # Choose base learners
  lrnr_glm <- make_learner(Lrnr_glm)
  lrnr_mean <- make_learner(Lrnr_mean)

  # Define metalearners appropriate to data types
  # non-negative least squares regression for continuous outcomes
  ls_metalearner <- make_learner(Lrnr_nnls)

  # mn_metalearner <- make_learner(Lrnr_solnp, metalearner_linear_multinomial,
  #                                loss_loglik_multinomial)

  # Plot Y to get a sense of distribution
  #hist(data2[[Y]])

  sl_Y <- Lrnr_sl $ new(learners = list(lrnr_mean, lrnr_glm),
                      metalearner = ls_metalearner)

  # Plot A to get a sense of distribution
  #hist(data[[A]]) # Actual A
  #hist(data2[[A]]) # Dichotomized A

  sl_A <- Lrnr_sl $ new(learners = list(lrnr_mean, lrnr_glm),
                      metalearner = ls_metalearner)#mn_metalearner)

  learner_list <- list(A = sl_A, Y = sl_Y)

  tmle_fit <- tmle3(ate_spec, data2, node_list, learner_list)
  print(tmle_fit)
}

# # Make a for loop function
tableFunc <- function (A, W, Y, data) {
#   # Make a dataframe to save results in
# resultTable <- data.frame(A = rep(1:length(A)),
#                           Y = rep(1:length(A)),
#                           #n = nrow(data),
#                           init_est = rep(1:length(A)),
#                           tmle_est = rep(1:length(A)),
#                           se = rep(1:length(A)),
#                           lower = rep(1:length(A)),
#                           upper = rep(1:length(A)))

# Run the function through a for loop 
# for (i in 1:length(A)) {
#     tmleResult <- tmleFunc(W, A[i], Y, data)
#     resultTable[i, 1] = A[i]
#     resultTable[i, 2] = Y
#     summary <- tmleResult $ summary
#     resultTable[i, 3] = summary $ init_est
#     resultTable[i, 4] = summary $ tmle_est
#     resultTable[i, 5] = summary $ se
#     resultTable[i, 6] = summary $ lower
#     resultTable[i, 7] = summary $ upper
# }

# Parallelize:
int.start.time <- Sys.time()
resultTable  <- foreach(i = 1:length(A), .combine = 'bind_rows',
                        .errorhandling = 'remove') %dopar% {
  tmleResult <- tmleFunc(W, A[i], Y, data)
  resultTable <- tmleResult $ summary
  resultTable $ A <- A[i]
  resultTable $ Y <- Y
  return(resultTable)
  }

int.end.time <- Sys.time()
difftime(int.end.time, int.start.time, units = "mins")

return(resultTable)
}
```

# HMO ELICIT
```{r, include=FALSE}
# Load data
hmo <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/hmoClean.RDS")
#dput(names((data)))
#head(data)

# Get mean and variance of the outcome
hist(hmo $ haz_6m)
mean <- mean(hmo $ haz_6m)
sd <- sd(hmo $ haz_6m)

# Generate new data from this distribution
hmo $ haz_6m_simulated <- rnorm(n = 199, mean = mean, sd = sd)
hmo $ haz_6m_simulated <- as.numeric(format(round(hmo $ haz_6m_simulated, 2), 
                                            nsmall = 2))

# Set parameters for tmleFunc
W = c("Secretor", "Diversity", "Evenness")
A = c("X2.FL", "X3FL", "DFLac", "X3.SL", "X6.SL", "LNT", "LNnT", "LNFP.I",
      "LNFP.II", "LNFP.III", "LSTb", "LSTc", "DFLNT", "LNH", "DSLNT", "FLNH",
      "DFLNH", "FDSLNH", "DSLNH", "SUM", "Sia", "Fuc")
Y = "haz_6m_simulated"

tableHmo <- tableFunc(A, W, Y, hmo)

# Save dataset
write.csv(tableHmo, file = "/data/imic/results/tmle/hmoElicitTMLE.csv")
```

# Biocrates normalized ELICIT
```{r}
# Load data
bioc <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/biocNormClean.RDS")
# head(bioc)
# dput(names((bioc)))

# Get mean and variance of the outcome
hist(bioc $ haz_6m)
mean <- mean(bioc $ haz_6m)
sd <- sd(bioc $ haz_6m)

# Generate new data from this distribution
bioc $ haz_6m_simulated <- rnorm(n = 199, mean = mean, sd = sd)
bioc $ haz_6m_simulated <- as.numeric(format(round(hmo $ haz_6m_simulated, 2), 
                                            nsmall = 2))

# Set parameters for tmleFunc
W = c("sex_base", "mage_base")
A = bioc %>%
  select(!c("bmid_base", "country", "studyid", "subjid", "subjido", "arm_base", 
            "sex_base", "brthyr_base", "brthweek_base", "mage_base", "parity_base", 
            "nlchild_base", "nperson_base", "nrooms_base", "meducyrs_base", 
            "h2osrcp_base", "cookplac_base", "inctot_base", "inctotu_base", 
            "epoch_base", "mhtcm_base", "mwtkg_base", "mbmi_base", "dlvloc_base", 
            "dvseason_base", "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", 
            "waz_base", "haz_base", "whz_base", "baz_base", "agedays_base", 
            "dur_bf_base", "dur_ebf_base", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", "haz_6m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "exbfdu_r_0to6m", 
            "fever_r_0to6m", "fever_r_6to18m", "cough_r_0to6m", "cough_r_6to18m", 
            "diarr_r_0to6m", "diarr_r_6to18m", "mhgb_18m", "muaccm_18m", 
            "muaz_18m", "bfdu_r_0to18m", "anti_r_0to18m", "haz_6m_simulated"))
A = colnames(A)
Y = "haz_6m_simulated"

tableBioc <- tableFunc(A, W, Y, bioc)

# Save dataset
write.csv(tableBioc, file = "/data/imic/results/tmle/biocElicitTMLE.csv")
```

# Bvitamin ELICIT
```{r}
# Load data
bvit <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/bvitClean.RDS")

# Get mean and variance of the outcome
hist(bvit $ haz_6m)
mean <- mean(bvit $ haz_6m)
sd <- sd(bvit $ haz_6m)

# Generate new data from this distribution
bvit $ haz_6m_simulated <- rnorm(n = 199, mean = mean, sd = sd)
bvit $ haz_6m_simulated <- as.numeric(format(round(bvit $ haz_6m_simulated, 2), 
                                            nsmall = 2))
#dput(names((bvit)))

# Set parameters for tmleFunc
W = c("sex_base", "mage_base")
A = bvit %>%
  select(!c("bmid_base", "country", "studyid", "siteid", "subjid", "subjido", 
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "inctot_base", 
            "inctotu_base", "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", 
            "mbmi_base", "pregout_base", "dlvloc_base", "dvseason_base", 
            "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", "waz_base", 
            "haz_base", "whz_base", "baz_base", "agedays_base", "feeding_base", 
            "dur_bf_base", "dur_ebf_base", "bmcol_fl_1m", "bmcol_fl_5m", 
            "agedays_1m", "agedays_5m", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", "haz_6m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "agedays_3m", "agedays_6m", 
            "agedays_9m", "agedays_12m", "agedays_15m", "agedays_18m", "visit_r_fl_0to6m", 
            "visit_r_fl_6to18m", "dur_r_0to6m", "dur_r_6to18m", "bfedfl_r_0to6m", 
            "exbfed_r_0to6m", "exbfdu_r_0to6m", "fever_r_0to6m", "fever_r_6to18m", 
            "cough_r_0to6m", "cough_r_6to18m", "diarr_r_0to6m", "diarr_r_6to18m", 
            "mhgb_18m", "muaccm_18m", "muaz_18m", "agedays_18m.1", "bfdu_r_0to18m", 
            "anti_r_0to18m", "haz_6m_simulated"))
A = colnames(A)
Y = "haz_6m_simulated"

tableBvit <- tableFunc(A, W, Y, bvit)

# Save dataset
write.csv(tableBvit, file = "/data/imic/results/tmle/BvitElicitTMLE.csv")
```

# Metabolomic Indicators ELICIT
```{r}
# Load data
metabol <- readRDS("/data/imic/data/raw_lab_data/elicit/merged_elicit/metabolClean.RDS")

# Get mean and variance of the outcome
hist(metabol $ haz_6m)
mean <- mean(metabol $ haz_6m)
sd <- sd(metabol $ haz_6m)

# Generate new data from this distribution
metabol $ haz_6m_simulated <- rnorm(n = 199, mean = mean, sd = sd)
metabol $ haz_6m_simulated <- as.numeric(format(round(metabol $ haz_6m_simulated, 2), 
                                            nsmall = 2))
#dput(names((metabol)))

# Set parameters for tmleFunc
W = c("sex_base", "mage_base")
A = metabol %>%
  select(!c("bmid_base", "country", "studyid", "siteid", "subjid", "subjido", 
            "studytyp", "arm_base", "sex_base", "brthyr_base", "brthweek_base", 
            "mage_base", "parity_base", "nlchild_base", "nperson_base", "nrooms_base", 
            "meducyrs_base", "h2osrcp_base", "cookplac_base", "inctot_base", 
            "inctotu_base", "epochn_base", "epoch_base", "mhtcm_base", "mwtkg_base", 
            "mbmi_base", "pregout_base", "dlvloc_base", "dvseason_base", 
            "wtkg_base", "lencm_base", "bmi_base", "hcircm_base", "waz_base", 
            "haz_base", "whz_base", "baz_base", "agedays_base", "feeding_base", 
            "dur_bf_base", "dur_ebf_base", "bmcol_fl_1m", "bmcol_fl_5m", 
            "agedays_1m", "agedays_5m", "lencm_3m", "lencm_6m", "lencm_9m", 
            "lencm_12m", "lencm_15m", "lencm_18m", "bmi_3m", "bmi_6m", "bmi_9m", 
            "bmi_12m", "bmi_15m", "bmi_18m", "hcircm_3m", "hcircm_6m", "hcircm_9m", 
            "hcircm_12m", "hcircm_15m", "hcircm_18m", "waz_3m", "waz_6m", 
            "waz_9m", "waz_12m", "waz_15m", "waz_18m", "haz_3m", "haz_6m", 
            "haz_9m", "haz_12m", "haz_15m", "haz_18m", "whz_3m", "whz_6m", 
            "whz_9m", "whz_12m", "whz_15m", "whz_18m", "baz_3m", "baz_6m", 
            "baz_9m", "baz_12m", "baz_15m", "baz_18m", "agedays_3m", "agedays_6m", 
            "agedays_9m", "agedays_12m", "agedays_15m", "agedays_18m", "visit_r_fl_0to6m", 
            "visit_r_fl_6to18m", "dur_r_0to6m", "dur_r_6to18m", "bfedfl_r_0to6m", 
            "exbfed_r_0to6m", "exbfdu_r_0to6m", "fever_r_0to6m", "fever_r_6to18m", 
            "cough_r_0to6m", "cough_r_6to18m", "diarr_r_0to6m", "diarr_r_6to18m", 
            "mhgb_18m", "muaccm_18m", "muaz_18m", "agedays_18m.1", "bfdu_r_0to18m", 
            "anti_r_0to18m","haz_6m_simulated"))
A = colnames(A)
Y = "haz_6m_simulated"

tableMetabol <- tableFunc(A, W, Y, metabol)

# Save dataset
write.csv(tableMetabol, file = "/data/imic/results/tmle/MetabolElicitTMLE.csv")
```

























